development:
  adtapter: mongoid
  sessions:
    default:
      database: virtual_congress
      hosts:
        - localhost:27017
production:
  adtapter: mongoid
  sessions:
    default:
      database: virtual_congress
      hosts:
        - localhost:27017        
